title: the whale
description: logbook of a tech journey
baseurl: "/"
url: "https://thewhale.dev"

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/thegreat-vanderlinde" }
    - { platform: telegram, user_url: "https://t.me/giacomo_cc" }
show_excerpts: true

plugins:
  - jekyll-feed
