title: the whale
description: logbook of a tech journey
baseurl: "/"
url: "https://thewhale.dev"

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/thegreat-vanderlinde" }
    - { platform: twitter, user_url: "https://twitter.com/vanderlinde____" }
plugins:
  - jekyll-feed
