title: the whale
description: logbook of a tech journey
baseurl: "/"
url: "https://thewhale.dev"
twitter_username: vanderlinde____
github_username: thegreat-vanderlinde

remote_theme: jekyll/minima
minima:
  skin: auto
plugins:
  - jekyll-feed
